kind: pipeline
type: kubernetes
name: default
steps:

  - name: extract git info
    image: alpine
    commands:
    - apk add git
    - export GIT_COMMIT=$(git rev-parse HEAD)
    - export BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
    - export REPO_NAME=$(basename -s .git `git config --get remote.origin.url`)
    - echo "$GIT_COMMIT"
    - echo "Branch=$BRANCH_NAME"
    - echo "Repository=$REPO_NAME"
    - exit 0 
  - name: maven-build
    image: maven:3.8-openjdk-17
    commands:
      - mvn clean package -DskipTests
      - echo "Maven build completed"
      - exit 0 
  - name: snyk scan
    image: maven:3.8-openjdk-17
    environment:
     SNYK_TOKEN:
      from_secret: snyk-auth-token
    commands:
     
      - curl -L https://static.snyk.io/cli/latest/snyk-linux -o snyk
      - chmod +x snyk
      - export SNYK_TOKEN=$SNYK_TOKEN
      
      - ./snyk test --severity-threshold=medium --org=ahmed1616-bo || true
      - ./snyk monitor --org=ahmed1616-bo
  - name: sonar-analysis
    image: sonarsource/sonar-scanner-cli:4.8
    environment:
      SONAR_HOST_URL: "http://192.168.3.100:30033"
      SONAR_TOKEN:
        from_secret: SONAR_TOKEN
    commands:
      - sonar-scanner -X -Dsonar.projectKey=absence -Dsonar.projectName=absence -Dsonar.projectVersion=1.0 -Dsonar.sources=src/main/java -Dsonar.host.url=http://192.168.3.100:30033 -Dsonar.login=admin -Dsonar.password=A@med22754008 -Dsonar.java.binaries=target/classes -Dsonar.java.source=17 -Dsonar.sourceEncoding=UTF-8 -Dsonar.exclusions="**/target/**,**/Dockerfile" -Dsonar.dependencyCheck.htmlReportPath=dependency-check-report.html -Dsonar.dependencyCheck.jsonReportPath=dependency-check-report.json