kind: pipeline
type: kubernetes
name: default
steps:

  - name: extract git info
    image: alpine
    commands:
    - apk add git
    - export GIT_COMMIT=$(git rev-parse HEAD)
    - export BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
    - export REPO_NAME=$(basename -s .git `git config --get remote.origin.url`)
  - name: maven-build
    image: maven:3.8-openjdk-17
    commands:
      - mvn clean package -DskipTests
      - echo "Maven build completed"
      - exit 0 
  - name: snyk scan
    image: node:20
    environment:
     SNYK_TOKEN:
      from_secret: snyk-auth-token
    commands:
    - curl -L https://static.snyk.io/cli/latest/snyk-linux -o snyk
    - chmod +x snyk
    - ./snyk auth $SNYK_TOKEN
    - ./snyk test --all-projects --org=ahmed1616-bo --severity-threshold=medium || true
    - ./snyk monitor --all-projects --org=ahmed1616-bo